# Generated by Django 3.0.8 on 2020-11-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Message date')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Readed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Chat', verbose_name='Chat')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
