# Generated by Django 3.0.8 on 2021-01-01 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogs', '0003_voicemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_message', models.TextField()),
                ('v_message', models.FileField(upload_to='')),
                ('sendtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Message date')),
                ('is_readed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Chat', verbose_name='Chat')),
            ],
        ),
    ]
