# Generated by Django 3.0.8 on 2021-01-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0004_message_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicemessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='voicemessage',
            name='chat',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sendtime']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='pub_date',
            new_name='sendtime',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='t_message',
            field=models.TextField(blank=True, verbose_name='Text message'),
        ),
        migrations.AddField(
            model_name='message',
            name='v_message',
            field=models.FileField(blank=True, upload_to='', verbose_name='Voice message'),
        ),
        migrations.DeleteModel(
            name='Message_v2',
        ),
        migrations.DeleteModel(
            name='VoiceMessage',
        ),
    ]
