# Generated by Django 3.0.8 on 2021-01-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0005_auto_20210101_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='t_message',
            field=models.TextField(blank=True, null=True, verbose_name='Text message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='v_message',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Voice message'),
        ),
    ]
