# Generated by Django 3.0.8 on 2021-01-01 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dialogs', '0006_auto_20210101_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sendtime',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='t_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='v_message',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=1, verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Message date')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Readed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Chat', verbose_name='Chat')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
