# Generated by Django 3.2.5 on 2021-07-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0007_auto_20210101_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
    ]
