# Generated by Django 3.0.8 on 2020-11-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
    ]
