# Generated by Django 3.0.8 on 2020-11-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
