# Generated by Django 3.0.8 on 2021-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201128_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-user-image.png', upload_to='profile_pics'),
        ),
    ]
