# Generated by Django 3.0.5 on 2020-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapairman',
            name='workshop_image',
            field=models.ImageField(default=True, upload_to='images/workshops/%Y/%m/%d/%H/%M/%S/'),
            preserve_default=False,
        ),
    ]
