# Generated by Django 3.0.6 on 2020-05-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rapairman_workshop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapairman',
            name='coord_h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rapairman',
            name='coord_v',
            field=models.FloatField(null=True),
        ),
    ]
