# Generated by Django 3.0.6 on 2020-05-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200527_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapairman',
            name='coord_h',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapairman',
            name='coord_v',
            field=models.FloatField(blank=True),
        ),
    ]
