# Generated by Django 3.0.6 on 2020-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200527_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapairman',
            old_name='about_rep',
            new_name='about_workshop',
        ),
        migrations.AddField(
            model_name='rapairman',
            name='worksop_name',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rapairman',
            name='coord_v',
            field=models.FloatField(),
        ),
    ]
