# Generated by Django 3.0.6 on 2020-05-31 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0005_auto_20200531_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worksop_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('workshop_image', models.ImageField(upload_to='images/workshops/%Y/%m/%d/%H/%M/%S/')),
                ('about_workshop', models.CharField(max_length=200)),
                ('services', models.TextField(max_length=500)),
                ('coord_v', models.FloatField()),
                ('coord_h', models.FloatField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repairman1',
            fields=[
                ('repairman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.Repairman')),
            ],
            bases=('map.repairman',),
        ),
        migrations.DeleteModel(
            name='Rapairman',
        ),
    ]
