# Generated by Django 3.0.6 on 2020-05-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200531_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repairman1',
        ),
    ]
