# Generated by Django 3.0.8 on 2020-09-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20200924_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairman',
            name='services',
        ),
        migrations.RemoveField(
            model_name='repairman',
            name='workshop_image',
        ),
        migrations.AddField(
            model_name='services',
            name='repairman',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='map.Repairman'),
            preserve_default=False,
        ),
    ]
