# Generated by Django 3.2.5 on 2021-07-26 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatroom_chatroommessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoomMessages',
            new_name='ChatRoomMessage',
        ),
    ]
