# Generated by Django 3.2.5 on 2021-07-27 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_chatroommessages_chatroommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessage',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatroommessage',
            name='message',
            field=models.TextField(max_length=255, verbose_name='messages'),
        ),
        migrations.AlterField(
            model_name='chatroommessage',
            name='messageAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
