# Generated by Django 3.2 on 2021-06-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
