# Generated by Django 3.0.2 on 2020-04-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200411_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_like',
        ),
    ]
