# Generated by Django 3.2 on 2021-06-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_commentproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mptt_level',
            new_name='level',
        ),
    ]
