# Generated by Django 3.2 on 2021-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_mptt_level_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default=123123, max_length=30),
            preserve_default=False,
        ),
    ]
